{
  "formatVersion": "1.1",
  "component": {
    "group": "kz.galamat",
    "module": "convenient-rpc-client-rabbitmq",
    "version": "0.0.12.b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "convenient-rpc-client-rabbitmq-0.0.12.b-plain.jar",
          "url": "convenient-rpc-client-rabbitmq-0.0.12.b-plain.jar",
          "size": 10573,
          "sha512": "b34103e22e3a906f49c5f21355a2c1c365fbf417eb9937da725d815c38aefc69b35a42a65ee4cfea75e0b688e343150d4774c5413166fc91efc431b5a809b82c",
          "sha256": "b845a7ea03b207f39a86caafb65e3bfd315e05abeb958be7ff4c3cfe560fa216",
          "sha1": "4973ba0d6ac04a03635f9690d5ad0df0bb98579f",
          "md5": "984059c1f55e4b576ccd702b0a50018b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "6.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "2.7.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-amqp",
          "version": {
            "requires": "2.7.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.thepavel",
          "module": "spring-icomponent",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "kz.galamat",
          "module": "convenient-rpc-interface",
          "version": {
            "requires": "0.0.8"
          }
        },
        {
          "group": "kz.galamat",
          "module": "convenient-rpc-rabbitmq-settings",
          "version": {
            "requires": "0.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "convenient-rpc-client-rabbitmq-0.0.12.b-plain.jar",
          "url": "convenient-rpc-client-rabbitmq-0.0.12.b-plain.jar",
          "size": 10573,
          "sha512": "b34103e22e3a906f49c5f21355a2c1c365fbf417eb9937da725d815c38aefc69b35a42a65ee4cfea75e0b688e343150d4774c5413166fc91efc431b5a809b82c",
          "sha256": "b845a7ea03b207f39a86caafb65e3bfd315e05abeb958be7ff4c3cfe560fa216",
          "sha1": "4973ba0d6ac04a03635f9690d5ad0df0bb98579f",
          "md5": "984059c1f55e4b576ccd702b0a50018b"
        }
      ]
    }
  ]
}
