{
  "formatVersion": "1.1",
  "component": {
    "group": "kz.galamat",
    "module": "convenient-rpc-client-rabbitmq",
    "version": "0.0.13.a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "convenient-rpc-client-rabbitmq-0.0.13.a-plain.jar",
          "url": "convenient-rpc-client-rabbitmq-0.0.13.a-plain.jar",
          "size": 10595,
          "sha512": "521aed6752122c72703d459d6dc6837505f503c331234e874d376ed3773b22d8252f8470cd7556745b14f9d61a08566a72f1c7d718ba85aaf3abc402b6be0f8e",
          "sha256": "fc944367162dc2eb75a69a05260f6607ad8a3e7eca70b4b714585a9d21f9af83",
          "sha1": "ded818f0991a3efde144176dcc4eb7f1ec8944e0",
          "md5": "4cc7ea253faffe5a1013c06ecd64e65b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "6.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "2.7.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-amqp",
          "version": {
            "requires": "2.7.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.thepavel",
          "module": "spring-icomponent",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "kz.galamat",
          "module": "convenient-rpc-interface",
          "version": {
            "requires": "0.0.8"
          }
        },
        {
          "group": "kz.galamat",
          "module": "convenient-rpc-rabbitmq-settings",
          "version": {
            "requires": "0.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "convenient-rpc-client-rabbitmq-0.0.13.a-plain.jar",
          "url": "convenient-rpc-client-rabbitmq-0.0.13.a-plain.jar",
          "size": 10595,
          "sha512": "521aed6752122c72703d459d6dc6837505f503c331234e874d376ed3773b22d8252f8470cd7556745b14f9d61a08566a72f1c7d718ba85aaf3abc402b6be0f8e",
          "sha256": "fc944367162dc2eb75a69a05260f6607ad8a3e7eca70b4b714585a9d21f9af83",
          "sha1": "ded818f0991a3efde144176dcc4eb7f1ec8944e0",
          "md5": "4cc7ea253faffe5a1013c06ecd64e65b"
        }
      ]
    }
  ]
}
