{
  "formatVersion": "1.1",
  "component": {
    "group": "kz.galamat",
    "module": "spring-boot-starter-rabbit-rpc-to-request-dispatcher",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-rabbit-rpc-to-request-dispatcher-0.0.2-plain.jar",
          "url": "spring-boot-starter-rabbit-rpc-to-request-dispatcher-0.0.2-plain.jar",
          "size": 34515,
          "sha512": "126b31becb4e7dc5c1fd9aeab6c29522ef9daea03c4a5ff6ab7382470ff6f2244ad014a1c1ebb07a68b12143cf13f182814fddad5f7758a69359dcb36e3e12ba",
          "sha256": "f53039a0e1ca9f31c76f3ffa4d66b7a4fa5714e555f0dc5bf4048fd0b32455e5",
          "sha1": "d19f6755214b573efd074075df4fcd58826d0445",
          "md5": "36942c74800d09ed4ba7a0236ec78b48"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-amqp",
          "version": {
            "requires": "2.7.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.7.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "2.7.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-rabbit-rpc-to-request-dispatcher-0.0.2-plain.jar",
          "url": "spring-boot-starter-rabbit-rpc-to-request-dispatcher-0.0.2-plain.jar",
          "size": 34515,
          "sha512": "126b31becb4e7dc5c1fd9aeab6c29522ef9daea03c4a5ff6ab7382470ff6f2244ad014a1c1ebb07a68b12143cf13f182814fddad5f7758a69359dcb36e3e12ba",
          "sha256": "f53039a0e1ca9f31c76f3ffa4d66b7a4fa5714e555f0dc5bf4048fd0b32455e5",
          "sha1": "d19f6755214b573efd074075df4fcd58826d0445",
          "md5": "36942c74800d09ed4ba7a0236ec78b48"
        }
      ]
    }
  ]
}
