{
  "formatVersion": "1.1",
  "component": {
    "group": "kz.galamat",
    "module": "convenient-rpc-client-rabbitmq",
    "version": "0.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "convenient-rpc-client-rabbitmq-0.0.10-plain.jar",
          "url": "convenient-rpc-client-rabbitmq-0.0.10-plain.jar",
          "size": 10556,
          "sha512": "be85c05605eafb25b338f6b003aa8c6a70ebcb03ea3d43a36d2594709ccd235e96369242027fd26ef721148ad3f107cba03ae7e91b4ce62afd756bb2f460729c",
          "sha256": "09d4b710e1b1766a3033bb290994547987639714dc28765220c84bb01d81f715",
          "sha1": "e333505ebd65199ac31b56688da684595e9f762d",
          "md5": "773dd69dc91761e524823f4ed661a26a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "2.7.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-amqp",
          "version": {
            "requires": "2.7.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.thepavel",
          "module": "spring-icomponent",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "kz.galamat",
          "module": "convenient-rpc-interface",
          "version": {
            "requires": "0.0.8"
          }
        },
        {
          "group": "kz.galamat",
          "module": "convenient-rpc-rabbitmq-settings",
          "version": {
            "requires": "0.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "convenient-rpc-client-rabbitmq-0.0.10-plain.jar",
          "url": "convenient-rpc-client-rabbitmq-0.0.10-plain.jar",
          "size": 10556,
          "sha512": "be85c05605eafb25b338f6b003aa8c6a70ebcb03ea3d43a36d2594709ccd235e96369242027fd26ef721148ad3f107cba03ae7e91b4ce62afd756bb2f460729c",
          "sha256": "09d4b710e1b1766a3033bb290994547987639714dc28765220c84bb01d81f715",
          "sha1": "e333505ebd65199ac31b56688da684595e9f762d",
          "md5": "773dd69dc91761e524823f4ed661a26a"
        }
      ]
    }
  ]
}
