{
  "formatVersion": "1.1",
  "component": {
    "group": "kz.galamat",
    "module": "convenient-rpc-client-rabbitmq",
    "version": "0.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "convenient-rpc-client-rabbitmq-0.0.10-plain.jar",
          "url": "convenient-rpc-client-rabbitmq-0.0.10-plain.jar",
          "size": 10559,
          "sha512": "6e63e15ce8d643a96c8d87e2c823eb9c78405c2b608e90b782f9cc9ba78e2078411ae50262798eb515a4bdd79dd6b3e271dfc91f8b08b5430b4d6cf291cc0618",
          "sha256": "21ca6fc0dad77fd12a884015ef93db121eac6a5b98a545c1b4737112672b7f1f",
          "sha1": "302ac8d58568eef2d6b5c24d0109a040186d466b",
          "md5": "2e363d7dea096702569fc8bc5b8ddc4e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "6.0.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "2.7.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-amqp",
          "version": {
            "requires": "2.7.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.thepavel",
          "module": "spring-icomponent",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "kz.galamat",
          "module": "convenient-rpc-interface",
          "version": {
            "requires": "0.0.8"
          }
        },
        {
          "group": "kz.galamat",
          "module": "convenient-rpc-rabbitmq-settings",
          "version": {
            "requires": "0.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "convenient-rpc-client-rabbitmq-0.0.10-plain.jar",
          "url": "convenient-rpc-client-rabbitmq-0.0.10-plain.jar",
          "size": 10559,
          "sha512": "6e63e15ce8d643a96c8d87e2c823eb9c78405c2b608e90b782f9cc9ba78e2078411ae50262798eb515a4bdd79dd6b3e271dfc91f8b08b5430b4d6cf291cc0618",
          "sha256": "21ca6fc0dad77fd12a884015ef93db121eac6a5b98a545c1b4737112672b7f1f",
          "sha1": "302ac8d58568eef2d6b5c24d0109a040186d466b",
          "md5": "2e363d7dea096702569fc8bc5b8ddc4e"
        }
      ]
    }
  ]
}
