{
  "formatVersion": "1.1",
  "component": {
    "group": "kz.galamat",
    "module": "convenient-rpc-client-rabbitmq",
    "version": "0.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "convenient-rpc-client-rabbitmq-0.0.7-plain.jar",
          "url": "convenient-rpc-client-rabbitmq-0.0.7-plain.jar",
          "size": 10254,
          "sha512": "a37bbe76c50ccaa4d375f5ba84be43bd80628784e2405d71e6e3db639dc86c25d56c3eb5e40d7d7a2d9d5e50c7bf668434bb61ff440505b1448c35214a6af8e1",
          "sha256": "60392ab099624408ad206c819174a46204db2cefd2eaaa82e37681dfc17af610",
          "sha1": "cb73fe67a83a4c0a90b610043c342685db3ba999",
          "md5": "0d7405e19ac4954195aec1f63c1b8929"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "5.3.23"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "2.7.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-amqp",
          "version": {
            "requires": "2.7.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.4.2"
          }
        },
        {
          "group": "org.thepavel",
          "module": "spring-icomponent",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "kz.galamat",
          "module": "convenient-rpc-interface",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "kz.galamat",
          "module": "convenient-rpc-rabbitmq-settings",
          "version": {
            "requires": "0.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "convenient-rpc-client-rabbitmq-0.0.7-plain.jar",
          "url": "convenient-rpc-client-rabbitmq-0.0.7-plain.jar",
          "size": 10254,
          "sha512": "a37bbe76c50ccaa4d375f5ba84be43bd80628784e2405d71e6e3db639dc86c25d56c3eb5e40d7d7a2d9d5e50c7bf668434bb61ff440505b1448c35214a6af8e1",
          "sha256": "60392ab099624408ad206c819174a46204db2cefd2eaaa82e37681dfc17af610",
          "sha1": "cb73fe67a83a4c0a90b610043c342685db3ba999",
          "md5": "0d7405e19ac4954195aec1f63c1b8929"
        }
      ]
    }
  ]
}
